version: '3.8'

services:
  main_app:
    container_name: "mainAppContainer"
    build: ./ExercisesFromBook  
    ports:
      - "5174:5174"
    environment:
      - HOST=0.0.0.0
        
  exercises_with_server:
    container_name: "exercisesWithServerContainer"
    build: ./Exercises_with_server
    ports:
      - "5173:5173"
      - "3001:3001"
    environment:
      - HOST=0.0.0.0