version: '3.8'

services:
  main_app:
    container_name: "mainAppContainer"
    image: toosie25/vue-sandbox-frontend:latest
    ports:
      - "5174:5174"
    environment:
      - HOST=0.0.0.0
        
  exercises_with_server:
    container_name: "exercisesWithServerContainer"
    image: toosie25/vue-sandbox-backend
    ports:
      - "5173:5173"
      - "3001:3001"
    environment:
      - HOST=0.0.0.0